version: 2.1
orbs:
  rust: circleci/rust@1.6.1
jobs:
  build_rust_linux_x86_64: &build_rust
    resource_class: medium
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - rust/install:
          version: 1.82.0
      - run: cargo --version
      - run: make symbolic
      - persist_to_workspace:
          root: .
          paths:
            - lib
  build_rust_linux_arm64:
    <<: *build_rust
    resource_class: arm.medium
  build_rust_macos_arm64:
    <<: *build_rust
    resource_class: macos.m1.medium.gen1
    machine: ~
    macos:
      xcode: 16.2.0
  build_go:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: .
      - run: make

workflows:
  build:
    jobs:
      - build_rust_linux_x86_64
      - build_rust_linux_arm64
      - build_rust_macos_arm64
      - build_go:
          requires:
            - build_rust_linux_x86_64
            - build_rust_linux_arm64
            - build_rust_macos_arm64
