version: 2.1

jobs:
  build-rust:
    parameters:
      rust_target:
        type: string
        default: x86_64-unknown-linux-gnu
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: rustup target add << parameters.rust_target >>
      - run: cargo --version
      - run:
          command: make symbolic
          environment:
            CARGO_BUILD_TARGET: << parameters.rust_target >>
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - include
  build-go:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: .
      - run: make

workflows:
  build:
    jobs:
      - build-rust:
          matrix:
            parameters:
              rust_target:
                - x86_64-unknown-linux-gnu
                - aarch64-unknown-linux-gnu
      - build-go:
          requires:
            - build-rust
