version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cargo --version
      - run: make symbolic
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - include
