version: 2.1

jobs:
  build-rust:
    docker:
      - image: cimg/rust:1.82.0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cargo --version
      - run: make symbolic
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - include
  build-go:
    docker:
      - image: cimg/golang:1.21.3
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make

workflows:
  build:
    jobs:
      - build-rust
      - build-go:
          requires:
            - build-rust
