version: 2.1

jobs:
  build-rust:
    parameters:
      resource_class:
        type: string
        default: medium
    docker:
      - image: cimg/rust:1.82.0
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: cargo --version
      - run: make symbolic
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - include
  build-go:
    docker:
      - image: cimg/go:1.21.3
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: .
      - run: make

workflows:
  build:
    jobs:
      - build-rust:
          matrix:
            parameters:
              resource_class:
                - medium
                - arm.medium
      - build-go:
          requires:
            - build-rust
